# Конфиг для парсинга данных с сайта barchart

# Адреса страниц для парсинга
url:
    price: "http://www.barchart.com/quotes/futures/"
    technical: "http://www.barchart.com/opinions/futures/"
    futuresall: "http://www.barchart.com/commodityfutures/All"

