# Конфиг для парсинга данных с сайта barchart

# адреса страниц
url:
    price: "http://www.barchart.com/quotes/futures/"
    technical: "http://www.barchart.com/opinions/futures/"

# кодовые обозначения (символы) торговых инструментов
# и соответствующие им названия классов-сущностей
symbols:
    ESU4: "Emini"
    ZSX14: "Soybeans"
    YMU4: "DJMini"
    CLV4: "CrudeOil"
    NGV4: "NaturalGas"
    GCZ4: "Gold"
    SIZ4: "Silver"
    ZWZ4: "Wheat"
    ZCZ4: "Corn"
