# Конфиг для парсинга данных с сайта barchart

# адреса страниц
url:
    price: "http://www.barchart.com/quotes/futures/"
    technical: "http://www.barchart.com/opinions/futures/"
    futuresall: "http://www.barchart.com/commodityfutures/All"

# кодовые обозначения (символы) торговых инструментов
# соответствующие им типы инструмента (futures, stocks, forex)
# и названия классов-сущностей
symbols:
    futures:
        ESU4: "Emini"
        YMU4: "DJMini"
        CLV4: "CrudeOil"
        NGV4: "NaturalGas"
        ZWZ4: "Wheat"
        ZCZ4: "Corn"
        ZSX14: "Soybeans"
        GCZ4: "Gold"
        SIZ4: "Silver"
