# Конфиг для парсинга данных с сайта barchart

# Адреса страниц для парсинга
url:
    price: "http://www.barchart.com/quotes/futures/"
    technical: "http://www.barchart.com/opinions/futures/"
    futuresall: "http://www.barchart.com/commodityfutures/All"
    # Адреса страниц с данными о ценах валютных пар
    forex:
        GBPUSD: "http://www.barchart.com/quotes/forex/British_Pound/US_Dollar/%5EGBPUSD"

# Настройки анализатора
analizer:
    # Период данных, используемых для сравнения результатов
    horizon:
        weeks: 1
        days: 0
        hours: 0
