parameters:
    barchart.config.class: Rottenwood\BarchartBundle\Service\ConfigService
    barchart.parser.class: Rottenwood\BarchartBundle\Service\BarchartParserService
    barchart.analizer.class: Rottenwood\BarchartBundle\Service\AnalizerService

services:
    barchart.config:
        class: %barchart.config.class%
        arguments: [@kernel]
    barchart.parser:
        class: %barchart.parser.class%
        arguments: [@barchart.config, @doctrine.orm.entity_manager]
    barchart.analizer:
        class: %barchart.analizer.class%
        arguments: [@barchart.config, @doctrine.orm.entity_manager]
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
