parameters:
    barchart.parser.class: Rottenwood\BarchartBundle\Service\BarchartParserService

services:
    barchart.parser:
        class: %barchart.parser.class%
        arguments: [@doctrine.orm.entity_manager, @kernel]
