parameters:
#    rottenwood_barchart.example.class: Rottenwood\BarchartBundle\Example

services:
#    rottenwood_barchart.example:
#        class: %rottenwood_barchart.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
