security:
    providers:
        hwi:
            id: hwi_oauth.user.provider

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        default:
#            anonymous: ~

      default:
          anonymous: ~
          oauth:
              resource_owners:
                  vkontakte:          "/login/check-vk"
#                  facebook:           "/login/check-facebook"
#                  google:             "/login/check-google"
#                  my_custom_provider: "/login/check-custom"
#                  my_github:          "/login/check-github"
              login_path:        /login
              use_forward:       false
              failure_path:      /login

              oauth_user_provider:
#                  service: hwi_oauth.user.provider.entity
                  oauth: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }